name: Tests CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Tests:
    name:  Tests
    runs-on: ubuntu-latest
    environment: test

    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install MySQL
      run: |
        sudo apt update
        sudo apt install -y mysql-server

    - name: Setup MySQL
      run: |
        sudo service mysql start
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};"
        sudo mysql -e "CREATE USER IF NOT EXISTS '${{ secrets.MYSQL_USER }}'@'%' IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON ${{ secrets.MYSQL_DATABASE }}.* TO '${{ secrets.MYSQL_USER }}'@'%';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Install Dependencies
      run: npm ci

    - name: Run Integration Tests
      run: npm test

    - name: Drop DB
      if: always()
      run: mysql -h 127.0.0.1 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e "DROP DATABASE IF EXISTS ${{ secrets.MYSQL_DATABASE }};"
